CREATE SCHEMA IF NOT EXISTS circus_city;
USE circus_city; 

CREATE TABLE  IF NOT EXISTS CONTACTS ( 
CONTACT_ID INT PRIMARY KEY, 
AREA_CODE CHAR (3), 
PHONE_NUMBER CHAR(7), 
EMAIL VARCHAR (50), 
ADDRESS VARCHAR (30), 
CITY VARCHAR (20), 
STATE VARCHAR (3), 
ZIP_CODE CHAR (5)
);


INSERT INTO CONTACTS VALUES(5, '303','6789808','electronicsfan@gmail.com', '513 S 5th St', 'Lakewood', 'CO', '80232'); 
INSERT INTO CONTACTS VALUES(6, '720','6789808','catlover@gmail.com', '2100 S Sequel St', 'Denver', 'CO', 80227); 
INSERT INTO CONTACTS VALUES(7, '303','6799801','johnsmith@aol.com', '1670 S Yes St', 'Denver', 'CO,', '80223'); 
INSERT INTO CONTACTS VALUES(8, '999','9999999','taxi@yahoo.com', '999 W West Dr', 'Aurora', 'CO', '80227'); 
INSERT INTO CONTACTS VALUES(9, '111','9017860','areacodehaver@rocketmail.com', '1890 W Alabama Dr', 'Denver', 'CO', '80227');
 
CREATE TABLE IF NOT EXISTS CUSTOMERS ( 
CUST_ID INT PRIMARY KEY, 
CUS_FNAME VARCHAR (20), 
CUS_LNAME VARCHAR (20), 
CONTACT_ID INT,
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (CONTACT_ID)
);
    
INSERT INTO CUSTOMERS VALUES(1, 'Sherry', 'Bolton', 5 ); 
INSERT INTO CUSTOMERS VALUES (2, 'John', 'Smith', 6 ); 
INSERT INTO CUSTOMERS VALUES(3, 'Jerry', 'Wiseman', 7); 
INSERT INTO CUSTOMERS VALUES(4, 'Rumple', 'Stiltskin', 8); 
INSERT INTO CUSTOMERS VALUES (5, 'Anna', 'Dostoyevich', 9);

CREATE TABLE IF NOT EXISTS JOBS (
JOB_ID INT PRIMARY KEY,
JOB_TITLE VARCHAR(20),
JOB_DESCRIPTION VARCHAR(50),
PAY_RATE DECIMAL(5,2)
);

INSERT INTO jobs VALUES(1, "Store Manager", "Oversee All Store Operations", 30.00);
INSERT INTO jobs VALUES(2, "Sales Representative", "Facilitate sales to customers", 20.00);
INSERT INTO jobs VALUES(3, "Accountant", "Track and audit company's finances", 28.00);
INSERT INTO jobs VALUES(4, "Custodian", "Maintain cleanliness of store", 15.00);
INSERT INTO jobs VALUES(5, "Warehouse Worker", "Restock shelves, maintain inventory", 18.00);

CREATE TABLE IF NOT EXISTS MANAGERS (
MANAGER_ID INT PRIMARY KEY,
MGR_FNAME VARCHAR(20),
MGR_LNAME VARCHAR(20),
DATE_HIRED DATE,
CONTACT_ID INT,
STORE_ID INT,

FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (CONTACT_ID)
);

INSERT INTO MANAGERS VALUES(100,"Mark","Zuckerberg","2004-05-24",5,1);
INSERT INTO MANAGERS VALUES(101,"Eren","Yeager","2005-01-15",6,1);
INSERT INTO MANAGERS VALUES(102,"Ava","Gremory","2005-04-16",7,1);
INSERT INTO MANAGERS VALUES(103,"Griffith","Hawk","2004-08-24",8,1);
INSERT INTO MANAGERS VALUES(104,"Legolace","Greenleaf","2018-06-05",9,1);


CREATE TABLE IF NOT EXISTS STORES (
STORE_ID INT PRIMARY KEY,
CONTACT_ID INT,
MANAGER_ID INT,

FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (CONTACT_ID),
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS (MANAGER_ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
EMP_ID INT PRIMARY KEY,
EMP_LNAME VARCHAR(20),
EMP_FNAME VARCHAR(20),
DATE_HIRED DATE,
JOB_ID INT,
CONTACT_ID INT,
MANAGER_ID INT,

FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (CONTACT_ID),
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS (MANAGER_ID)
);

CREATE TABLE IF NOT EXISTS VENDORS (
VENDOR_ID INT PRIMARY KEY,
VENDOR_NAME VARCHAR(20),
REP_LNAME VARCHAR(20),
REP_FNAME VARCHAR(20),
CONTACT_ID INT,

FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (CONTACT_ID) 
);

CREATE TABLE IF NOT EXISTS PROD_CATEGORIES (
CATEGORY_ID INT PRIMARY KEY,
CAT_NAME VARCHAR(20),
CAT_DESCRIPTION VARCHAR(100)
);

INSERT INTO PROD_CATEGORIES VALUES (1, "Computer Monitors",  "Computer monitors from brands including Dell, HP, Samsung, and others.");
INSERT INTO PROD_CATEGORIES VALUES (2, "Computer Mice",  "Computer mice from brands including Logitech, HP, Dell, Razer, and others.");
INSERT INTO PROD_CATEGORIES VALUES (3, "Computer Parts",  "Computer Parts like Motherboards, GPU, CPU, Storage, RAM, and others.");
INSERT INTO PROD_CATEGORIES VALUES (4, "Pre Built Desktop Computers", "Desktop Computers from brands like Apple, HP, Dell, Lenovo, and others.");
INSERT INTO PROD_CATEGORIES VALUES (5, "Laptop Computers", "Laptop computers from brands like Microsoft, HP, Dell, Google, and others");

CREATE TABLE IF NOT EXISTS PRODUCTS (
PRODUCT_ID INT PRIMARY KEY,
CATEGORY_ID INT,
PRODUCT_NAME VARCHAR(20),
P_DESCRIPTION VARCHAR(50),
PRICE DECIMAL(6,2),
P_DISCOUNT DECIMAL (2,2),
VENDOR_ID INT,

FOREIGN KEY (CATEGORY_ID) REFERENCES PROD_CATEGORIES (CATEGORY_ID),
FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS (VENDOR_ID)
); 

INSERT INTO PRODUCTS VALUES (1,1,"LG 24 Inch Monitor","LG 24 inch LCD Monitor 1080p resolution 60hz",75.99,0.10,1);
INSERT INTO PRODUCTS VALUES (2,2,"HP Wireless Mouse","HP Wireless Computer Mouse with Silent Clicking",14.99,0.0,1);
INSERT INTO PRODUCTS VALUES (3,3,"MSI Computer Motherboard","5000+MHZ 6gbs per second Motherboard",179.95,0.0,1);
INSERT INTO PRODUCTS VALUES (4,4,"Dell Desktop Computer","12 gen intel core, Windows 11, GTX 1660, 16gb ram, 1tb storage Desktop Computer",1100.99,0.25,1);
INSERT INTO PRODUCTS VALUES (5,5,"Microsoft Surface Laptop","Surface Laptop Go 2 - Ice Blue, Intel Core i5, 8GB RAM, 128GB SSD",599.99,0.15,1);

CREATE TABLE IF NOT EXISTS INVOICES (
INVOICE_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
EMP_ID INT,
INVOICE_DATE DATE,

FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUST_ID),
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES (EMP_ID)
);

-- change emp_id if needed
INSERT INTO invoices VALUES(100, 1, 30, "2022-11-01"); 
INSERT INTO invoices VALUES(101, 2, 31, "2022-11-02"); 
INSERT INTO invoices VALUES(102, 4, 33, "2022-11-03"); 
INSERT INTO invoices VALUES(103, 2, 31, "2022-11-04"); 
INSERT INTO invoices VALUES(104, 3, 34, "2022-11-05"); 


CREATE TABLE IF NOT EXISTS LINE_ITEMS (
INVOICE_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
QTY INT,
LINE_PRICE DECIMAL(8,2),

PRIMARY KEY(INVOICE_ID, PRODUCT_ID),
FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES (INVOICE_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);

INSERT INTO line_items VALUES(100, 1, 2, 136.78);
INSERT INTO line_items VALUES(101, 2, 1, 14.99);
INSERT INTO line_items VALUES(102, 3, 1, 179.95);
INSERT INTO line_items VALUES(103, 4, 1, 825.74);
INSERT INTO line_items VALUES(104, 5, 1, 509.99);


CREATE TABLE IF NOT EXISTS STORE_INV (
STORE_ID INT,
PRODUCT_ID INT,
P_INVENTORY INT,

PRIMARY KEY (STORE_ID, PRODUCT_ID),
FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);

INSERT INTO STORE_INV VALUES(1,1,15);
INSERT INTO STORE_INV VALUES(1,2,36);
INSERT INTO STORE_INV VALUES(1,3,9);
INSERT INTO STORE_INV VALUES(1,4,11);
INSERT INTO STORE_INV VALUES(1,5,23);

 

 



 

 
